# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'LTIM_CLOUDLAB_SUB'
    subscriptionId: 'f83aae0f-b5dd-4ce9-8483-a007ea91312b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'sourishwebapp'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '*.json'
    deploymentMode: 'Incremental'
